### ISSUE TITLE
Clear list of available packages before refreshing it

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#101]
When opening the list of packages, there is a moment when we see outdated data, before it refreshes. This is true when selecting a package (when viewing the list I see the package for a second, then it disappears), and it even happened to me when switching users (I saw the other user's packages for a second).

The simplest solution, IMO, is to always clear the list before refreshing, but if you have a simpler one feel free to offer it.

**Comment by DenisDemyanko** [comment]
Added in [7fa2a0f ](https://github.com/paket-core/mobile/commit/7fa2a0f689a7879bddad7c66b4f57d816c037180)
