### ISSUE TITLE
Use Bridge server instead of stellar sdk for common opperations. 

### ISSUE THREAD

**Issue by yaroslavr-itd** [paket-core/mobile#107]
Need to make sure, that all stellar-operations are made through our Bridge server. It will allow automatically change some parts without need to rebuild mobile app. As far as I know, now "allow trust" operation made directly through stellar sdk. We need to change that to `/prepare_trust` usage on our Bridge server.

Also, need to clean up project from hardcode (as far as I know, now when "allow trust" operation is run hardcoded ISSUER seed is used)

There is the list of endpoints, you can use:
  * `/bul_account` - return information about stellar account
  * `/prepare_account ` - prepare creating account transaction
  * `/prepare_escrow` -prepare escrow transactions
  * `/prepare_relay` - prepare relay transactions
  * `/prepare_send_buls` - prepare payment transaction
  * `/prepare_trust` - prepare allow trust transaction
  * `/submit_transaction` - submit transaction to horizon server

All `prepare` transaction should be signed by appropriate secret keys and sent via`/submit_transaction`

**Comment by israellevin** [comment]
:+1: 

Note that this is about to change in the future, when we phase out the bridge server (see #106), but we have to do it when we are all on the same page.

**Comment by DenisDemyanko** [comment]
Added in [ea1c906](https://github.com/paket-core/mobile/commit/ea1c906c7f2ab27bb1933320f250f539a8db84d1)
