### ISSUE TITLE
Reorder package info page

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#112]
The package info page should show info in the following order:
1) Top level (non foldable) should include payment and collateral, so "funds" section should disappear
2) Escrow pubkey should change to short-code
3) Location
4) Information
5) Users (add escrow pubkey to top of this list and rename it to "accounts")
6) Events

**Comment by DenisDemyanko** [comment]
Added in [a2de924](https://github.com/paket-core/mobile/commit/a2de92454a38c3ed890befd7885cea2e45f56c91)
