### ISSUE TITLE
Smaller "more settings" button in login screen

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#113]
Currently it is very ugly and on my phone it is half hidden at bottom of screen. We should probably make it  just with an icon of gears, and move it to one of the top corners. Please fix it like that for now and consult with Serge for exact future design. The general guideline is that it should not attract attention. Only expert users should use it.

**Comment by DenisDemyanko** [comment]
Added in [a2de924](https://github.com/paket-core/mobile/commit/a2de92454a38c3ed890befd7885cea2e45f56c91)
