### ISSUE TITLE
Remove all mentions of PaKeT global

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#116]
The name "paket" should only appear in "powered by PAKET". All other mentions of it should be removed. If you have a place where you are not sure what to put instead, please list it in this ticket and we will decide.

**Comment by DenisDemyanko** [comment]
Added in [d0ecae7](https://github.com/paket-core/mobile/commit/d0ecae750aa50020f56df94dae707ac58c1e1c23)
