### ISSUE TITLE
Small maps are hard to read

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#118]
The little circles with a map in them are very hard to read. They are a bit too small, and too zoomed in. You can change the zoom right away. As for the size - try increasing it a bit. Maybe we can even lay them out one below the other, or replace them with a bigger map that shows the whole route... Consult with Serge if you are unsure.

**Comment by owlen** [comment]
For now no need to change the zoom.
Also, maybe leave it square instead of round.

**Comment by DenisDemyanko** [comment]
Added in [d0ecae7](https://github.com/paket-core/mobile/commit/d0ecae750aa50020f56df94dae707ac58c1e1c23)

**Comment by owlen** [comment]
Looks better zoomed. I'm moving to done and opening a new ticket for style.
