### ISSUE TITLE
Always include country warning

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#119]
The warning we give in registration form when user is from the US should always appear there (of course, only in the case he chooses US do we actually give an error), and at the end of the warning a link saying "read why" that points to this URL: https://medium.com/@oren_gampel/paket-not-in-the-usa-2872cbc70907

**Comment by DenisDemyanko** [comment]
Added in [d0ecae7](https://github.com/paket-core/mobile/commit/d0ecae750aa50020f56df94dae707ac58c1e1c23)
