### ISSUE TITLE
Autocomplete call signs

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#120]
When the user fills in a call-sign, the app should offer completions from all registered call-signs. This will require a new anonymous endpoint in funder called "callsigns" which returns all registered call-signs. @yaroslavr-itd will take care of it (it's very similar to the debug users call).

**Comment by DenisDemyanko** [comment]
Added in [d0ecae7](https://github.com/paket-core/mobile/commit/d0ecae750aa50020f56df94dae707ac58c1e1c23)
