### ISSUE TITLE
Disable submit button on some states

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#125]
1) In login form, the "restore account" should be disabled until a mnemonic or a seed is typed
2) In send bul form the "send" button should be disabled until recipient and amount are filled
3) In purchase BUL and XLM "purchase" button should be disabled until payment currency and amount are filled
4) In profile page the "update profile" button should be disabled until some details have changed

**Comment by DenisDemyanko** [comment]
@israellevin 
How about other pages?
Should I add on these pages?

1. Registration
2. SMS Verification 
3. Launch Package
4. Settings

**Comment by israellevin** [comment]
Good thinking!

1. Yes
2. Yes
3. I think no, because it's a long form, and we rather jump to the missing field than have the user frustrated with the disabled button and searching for the missing field himself (or cursing and uninstalling the app)
4. Yes, like in profile page - only enable button if changes were made

**Comment by DenisDemyanko** [comment]
Added in [687ed6a4](https://github.com/paket-core/mobile/commit/687ed6a4966a1e9d119e65e101ff981e300ebc94)
