### ISSUE TITLE
Show title of missing fields when jumping to them

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#128]
When a submit button is clicked on a form that has missing fields, the cursor usually jumps so that the first missing field is on the top of the screen. However, if the field has a heading, it often remains hidden beyond the top. We need that title to be visible so it will be clear to the user.

**Comment by DenisDemyanko** [comment]
Added in [d0ecae7](https://github.com/paket-core/mobile/commit/d0ecae750aa50020f56df94dae707ac58c1e1c23)
