### ISSUE TITLE
Improve background process behaviour

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#135]
Guidelines for new behaviour:
1. The background process wakes up every X minutes (current default is 10, but add an option to the advanced settings screen to change it), sends events if required, and shuts down - the user only sees it running when it asks for location, like whatsapp
2. Notifications still arrive quickly, even if the background process is not shown as running

I understand that this requires push notifications, so please give a short description of what that means and what is needed for it in this thread.

This is related to #92.

**Comment by DenisDemyanko** [comment]
Added in [7fa2a0f ](https://github.com/paket-core/mobile/commit/7fa2a0f689a7879bddad7c66b4f57d816c037180)
