### ISSUE TITLE
Generate / restore key arrows not responsive when keyboard is shown

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#16]
When the keyboard is shown, hitting the arrows only hides the keyboard.

Also, I'm not happy with them being arrows, something about it feels weird. Maybe just because we discussed it too much. Let's talk to Serge again about this.

**Comment by AndreusExx** [comment]
Fixed in 7cbc5d864d4b9c2f8210d065c00d7f332e8b77c8
