### ISSUE TITLE
Flicker in splash screen

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#18]
When starting the application, the splash screen is shown, and then it flickers a bit and is shown again. Not a critical issue, but would be nice to fix.

**Comment by AndreusExx** [comment]
I can't reproduce this. What is the model of the phone and Android version?

**Comment by israellevin** [comment]
Mine is Redmi note 4X - Android 6.0 MRA58K, but we also see this on Oren's HTC 10.

**Comment by AndreusExx** [comment]
Fixed in 865fda715c30a7f726ae6aba3b81bb0fc026ecb8
