### ISSUE TITLE
Call-sign can't be edited when empty

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#19]
I can't reproduce this, and I don't understand how I got to that state, but I restored an existing stellar account that trusts buls from the seed, and I got to a form for filling in my details, but I could not focus the call-sign field to fill it.

@AndreusExx, you got any idea what can cause this? Maybe the fact that once it is set that field becomes non-editable?

**Comment by israellevin** [comment]
Ah, I managed to reproduce. It happens when you have a user with a call-sign and everything, but no kyc data. It seems the call-sign field is not being retrieved at this point. Only after I fill in all the kyc data, logout, and login again - do I see the call-sign.

**Comment by AndreusExx** [comment]
Please clarify to me, what is treated like kyc data?

**Comment by israellevin** [comment]
All the user details that are not the call-sign. Currently full-name, address, and phone number. In the future, we will surely have more.

**Comment by AndreusExx** [comment]
As I remember the the stopping field was Address. From the current flow we can't have a user without all data.

**Comment by israellevin** [comment]
It's an open API, so there is nothing stopping users from being created by other apps, or even directly from the swagger page. So this still needs to be handled.

**Comment by AndreusExx** [comment]
So considering this: "Currently full-name, address, and phone number. In the future, we will surely have more." and this: "It happens when you have a user with a call-sign and everything, but no kyc data". What is the actual problem?

**Comment by AndreusExx** [comment]
When the user does not have information about the address, phone, name: /user_infos API call does not return a public key. Probably we must add a call_sign key in the response in any case, even if the user does not have KYC data?

Sending request to: v2/user_infos, Method: POST
Status: OK, Content: {
"status": 200, 
"user_details": { }
}

**Comment by israellevin** [comment]
As far as I can tell, user_infos NEVER returns the call_sign or the pubkey. This data is retrieved from the get_user endpoint.

Perhaps it's a good idea to have user_infos return that data as well, but I think this is still a bug in the flow of the app. How come you have this data after filling out the kyc details and logging out? Is this what happens on line 50 of `Models/ProfileModel.cs`?

**Comment by AndreusExx** [comment]
Yes, indeed you are right.

**Comment by AndreusExx** [comment]
Fixed in b6694695c77cee8fcfe650e675685d26eebe4ee3
