### ISSUE TITLE
Misleading "transaction complete" message

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#20]
When asking to purchase XLM or BUL, after the user is given the address there is a message stating "transaction complete". That is highly misleading, since the user was only given a payment address, and the transaction will not be complete before he sends funds, we notice, and send him his.

**Comment by AndreusExx** [comment]
What should be the correct message?

**Comment by israellevin** [comment]
Let's use "awaiting payment" for the moment, and #31 will make it trivial to change.

**Comment by AndreusExx** [comment]
Fixed in 7cbc5d864d4b9c2f8210d065c00d7f332e8b77c8
