### ISSUE TITLE
Switching from BUL to XLM in wallet is not clear

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#21]
I like the sideways sliding between BUL and XLM wallet, but when first using the app it is not clear to the user that there is another wallet to switch to. Please discuss this with Serge.

Perhaps it will suffice to show a bit more of the "hidden" wallet, so it will be tempting to scroll to it. Perhaps there should be some indication ("XLM wallet ->" and "<-BUL wallet"). Not sure.

**Comment by AndreusExx** [comment]
Please provide some screenshots, how do you see this.

**Comment by AndreusExx** [comment]
And what is the device model and it's screen size?

**Comment by israellevin** [comment]
It's a redmi note X4 and HTC 10 (my phone and Oren's), see screenshot here: https://imagebin.ca/v/49mvQoixmro6

**Comment by AndreusExx** [comment]
Fixed in 7cbc5d864d4b9c2f8210d065c00d7f332e8b77c8
