### ISSUE TITLE
Some phones do not show wallet fields

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#22]
On Oren's phone, which is HTC, when I click Send BUL, Purchase BUL, and Purchase XLM, I see the form expanding, but it remains completely empty. See here: https://imagebin.ca/v/49m041s0esj2

**Comment by israellevin** [comment]
HTC 10.

**Comment by AndreusExx** [comment]
and Android version too

**Comment by AndreusExx** [comment]
Ok, we will have HTC E8 tomorrow, maybe we can reproduce it there too.

**Comment by AndreusExx** [comment]
Testing a solution by disabling animation in 439fb7ba9c64c08a9b1f79d83194df914496cf07

**Comment by owlen** [comment]
@AndreusExx On the latest version I can see all the fields and it works well.
Will return to progress for you to decide whether you want to research the animation or leave it without it.

**Comment by AndreusExx** [comment]
Fixed in 102d33f7a34a24c75a8aba80ca3383d2848e44f0

**Comment by owlen** [comment]
I can see all the fields well in ver 1.1.9. I'm not sure if there is some animation when I switch between them.
