### ISSUE TITLE
Some phones show generic icon for the app

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#23]
On Oren's phone, HTC, the app icon is the default green android icon.

**Comment by AndreusExx** [comment]
Waiting icons from Serge.

**Comment by DenisDemyanko** [comment]
Added in [412ac91](https://github.com/paket-core/mobile/commit/412ac913712991d1582dcde16525daffdc6ab18d)

**Comment by israellevin** [comment]
Works! Now we just need a good looking icon :)
