### ISSUE TITLE
Add proper errors for invalid / nonexistent user

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#24]
When entering an invalid or nonexistent user in any of the forms, we get a very ugly debug error. Let's make it something nicer. And please lmk if you need the server to return clearer errors.

**Comment by AndreusExx** [comment]
Yes, we need to discuss this.

**Comment by israellevin** [comment]
OK, this is officially the discussion page, let's discuss :)

**Comment by AndreusExx** [comment]
So, I think we need some kind of error pattern in response json, if server repots an error. It would be good to have there: status code, text message in english, internal error code.
"Internal error code" is Int value, that would be represented by some ServiceErrorEnum in mobile application. This can give us a certain definition of what exact error has occurred, so then we can substitute it with proper localized string.

**Comment by AndreusExx** [comment]
Can we make it a separate json object called "error" and add it to response, if there is some error? It would be easier to handle this on client.

**Comment by israellevin** [comment]
This already exists (as well as a "debug" string when running in debug mode), but it's only in English. I think adding an error number is a pretty good idea.

**Comment by AndreusExx** [comment]
No, you don't get an idea. I mean something like that:

**Comment by israellevin** [comment]
I do not understand why error has to be the parent. Currently errors return something like:
```json
{
  "debug": "something",
  "error": "something",
  "status": 404
}
```

It is perfectly acceptable to check for the existence of this field. The server's code actually does this:
```python
if 'error' in response:
```

**Comment by AndreusExx** [comment]
It would be more comfortable to handle this on client.

**Comment by AndreusExx** [comment]
Nonexistent user error fixed in 1f112d6628522980906436084a5a04326e3db894. Waiting for server updates with error codes.

**Comment by AndreusExx** [comment]
Nonexistent user error fixed in 1f112d6628522980906436084a5a04326e3db894. Waiting for server updates with error codes.

**Comment by israellevin** [comment]
Server now has error codes taken directly from status code. Once we compile a list of codes we can change them accordingly.

**Comment by AndreusExx** [comment]
Updated in 72ffa8fbabda4ffcc851053d81cd36b2bd60c3b7
