### ISSUE TITLE
Remove "loading" text messages

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#25]
The text "loading" is not required, and sometimes misleading. Everyone knows what a spinner means.

**Comment by AndreusExx** [comment]
Fixed in 3ce937bb8d3ddb1460274d8fb207f6e4884f57bb

**Comment by israellevin** [comment]
The text was removed, but the spinner is no longer spinning on the HTC.

**Comment by AndreusExx** [comment]
Updated in #7371d2750cfb55dff5d2151e427e5d7699680a4c

**Comment by AndreusExx** [comment]
Updated in 7371d2750cfb55dff5d2151e427e5d7699680a4c

**Comment by AndreusExx** [comment]
Fixed in 7371d2750cfb55dff5d2151e427e5d7699680a4c

**Comment by AndreusExx** [comment]
Updated in 7371d2750cfb55dff5d2151e427e5d7699680a4c

**Comment by owlen** [comment]
In 1.1.9: No text but spinner doesn't spin.

**Comment by AndreusExx** [comment]
Updated in 1f112d6628522980906436084a5a04326e3db894 for HTC 10.

**Comment by AndreusExx** [comment]
Updated in 1f112d6628522980906436084a5a04326e3db894 for HTC 10.
