### ISSUE TITLE
Send BUL and Purchase BUL expand at the same time on some phones

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#27]
While both actions belong to the same subject (BUL wallet), they are completely different and distinct actions, so perhaps having them both open one below the other is not a good idea.

Please discuss this with Serge.

**Comment by AndreusExx** [comment]
Implementation should already be exact as described here. Please provide phone model, system version and some screenshot of that issue.

**Comment by israellevin** [comment]
See screen capture and phone model in #22.

**Comment by AndreusExx** [comment]
Testing a solution by disabling animation in 439fb7ba9c64c08a9b1f79d83194df914496cf07

**Comment by israellevin** [comment]
Works. Moving back into to do column.

**Comment by AndreusExx** [comment]
Fixed in 102d33f7a34a24c75a8aba80ca3383d2848e44f0
