### ISSUE TITLE
Notifications can't be dismissed

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#28]
When notifications show up, there is no way to dismiss them, you just have to wait for them to go away. It should be possible to slide them aside to get rid of them.

**Comment by AndreusExx** [comment]
We can't reproduce this issue right now. The way it can be dismissed is a tap or swipe up.

**Comment by israellevin** [comment]
Ah. Tap seems to work on my phone (redmi note X4), but swipe does not.

**Comment by AndreusExx** [comment]
Updated in 613d34d4e9aa7b9eeed36f49193509862046a3ce
