### ISSUE TITLE
Create paket URIs

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#32]
We want to have URIs in the form `paket://packages/GDVFXBI6OG` or something like that, so it will be possible, e.g., to send a package's details through a text message instead of scanning a QR code, or to send a link that will directly open a specific package details page. Stuff like that.

How is this done?

**Comment by AndreusExx** [comment]
So the goal is to provide way to open package acceptance page via a link, right? Please describe the process. I guess wi should have some extra functionality in package details to share this things.

**Comment by israellevin** [comment]
In the future, we will surely have a way to share package and / or copy this url to the clipboard, but right now let's assume that I am typing the URL by hand into an SMS message, and I want it to open in the app. How do I do that?

**Comment by AndreusExx** [comment]
This can easily be achieved bu deep linking system. It would be just an app specific URI, which would contain Escrow Pubkey as it's argument.

**Comment by israellevin** [comment]
Cool. Can we do it for next milestone?

**Comment by AndreusExx** [comment]
Yes

**Comment by AndreusExx** [comment]
Added in b43442c0c43f656d1e85895985c4891c5fe571b8

**Comment by israellevin** [comment]
@AndreusExx (or @DenisDemyanko ), please share a URI that I can click and see the details of a specific package.

**Comment by DenisDemyanko** [comment]
@israellevin 

I created a temporary link that will be available within 24 hours
Enter the desired ID in the text box and click "start my app"

Link = https://a.uguu.se/mp6H1GXPlkJU_deeplink.html

Also you can download the html-page = https://www.dropbox.com/s/8pi4f090i9vlmtt/deeplink.html?dl=0

**Comment by israellevin** [comment]
This works, so I am closing the issue. To actually use it properly, we need to create an http(s) endpoint with JS that will set the location to a paketglobal:// URI, or to a playstore/download URI if that fails.
