### ISSUE TITLE
Can't re-install app without uninstalling first

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#35]
Both my phone and Oren's refuse to re-install. After clicking the "install" button we get a message "app not installed". This is a new regression.

**Comment by AndreusExx** [comment]
Can't reproduce.

**Comment by AndreusExx** [comment]
Please check Milestone_1.1.9 branch

**Comment by israellevin** [comment]
This happened again. @DenisDemyanko , please document the solution here once you find it.

**Comment by DenisDemyanko** [comment]
This error has occurred because the apk is signed with a developer key which is different form Andrey key. The keys are going to be synced and this error shouldn’t occur in future.
