### ISSUE TITLE
Write a build guide

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#36]
We need this for the website - a guide of how to get from the git repository to a working apk.

**Comment by AndreusExx** [comment]
What do we need except of "clone repository and build it"?

**Comment by israellevin** [comment]
An explanation of how to build it for people who have no idea how to do it (or what xamarine is).

**Comment by AndreusExx** [comment]
Added in 572c7f041152561545a7b6c01253e7747d6f4718
