### ISSUE TITLE
Add a three letter code to each package

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#38]
Discuss with Serge how to do this, but we want to display the last three characters of the escrow pubkey and display it as some kind of short package ID. So we can tell eachother "I launched package XYZ".

**Comment by DenisDemyanko** [comment]
Added in [9f2a3c0](https://github.com/paket-core/mobile/commit/9f2a3c0043078f791b8fe3461206cd7e7ab6781b)

**Comment by israellevin** [comment]
We have decided to move this into the server, so as to have a unified short package ID, see here: https://github.com/paket-core/router/issues/14

**Comment by DenisDemyanko** [comment]
Added in [2092602](https://github.com/paket-core/mobile/commit/209260215e40c5c7b7e3a324619879aed8851334)

**Comment by israellevin** [comment]
I opened #108, but now I understand it may be redundant. Moving it to "needs review".
