### ISSUE TITLE
Add data to package screen

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#42]
The package screen should contain the escrow_pubkey and the pubkey and call-sign if there is one of the launcher, the recipient. Also, in package details we want to see an expandable list of all the events, with pubkey+call-sign of the user in every event.
 
Also, the sent field does not seem to be getting the correct value. I suspect it is looking for the wrong key in the response JSON.

**Comment by israellevin** [comment]
Oh, and all the pubkeys and call-signs should be copyable.

**Comment by israellevin** [comment]
We also want to show the URLs for the package. Generally, we probably want all the information that the package JSON returns.

**Comment by DenisDemyanko** [comment]
Added in [9f2a3c0](https://github.com/paket-core/mobile/commit/9f2a3c0043078f791b8fe3461206cd7e7ab6781b)
