### ISSUE TITLE
Add about button

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#46]
Add a button that shows "about" info. Version, URL of app page (currently just github repo), URL of PAKET, and we will add more info later.

**Comment by DenisDemyanko** [comment]
Please explain me
1) Where should be the button? - http://prntscr.com/ki64ut or http://prntscr.com/ki65bn
2) What is "URL of PAKET"?

**Comment by israellevin** [comment]
URL of PAKET is https://paket.global

As for location of the about button, please discuss with Serge.

**Comment by DenisDemyanko** [comment]
Added in [bfe5b86](https://github.com/paket-core/mobile/commit/bfe5b86ad72a078059b7263d2bb58f066eb25753)
