### ISSUE TITLE
Add translation mechanism

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#48]
Add a language selection button (maybe in the same menu that has the about button from #46) and write a short explanation of how to add new languages. Maybe even translation to Russian for some of the texts. This should be done through the mechanism Andrey has put in place from #31).

**Comment by DenisDemyanko** [comment]
The mechanism implemented in task #31 supposed that language is going to be selected automatically depending on user phone localization and language. It’s not possible to select language within the app.

**Comment by DenisDemyanko** [comment]
@israellevin 

**How to add localization**

Here is an example of the main localization file in English - [Resources.resx](https://www.dropbox.com/s/tp99ph05f366z7z/Resources.resx?dl=0)
The file is structured as an XML document.
Change the extension to xml and open it.

To add localization, for example, Russian we must:

1) Copy the main file and name it _Resources.ru.resx_ (The general pattern is to use two-letter language codes)
2) Substitute the text in English which is in the “value” currently with the text in Russian.

_OR_

I can provide you with just a text file, with a set of words and sentences that need to be translated. You fill the file and give it to me.

**Comment by israellevin** [comment]
>  It’s not possible to select language within the app.

We need to fix this.

**Comment by DenisDemyanko** [comment]
Added in [bfe5b86](https://github.com/paket-core/mobile/commit/bfe5b86ad72a078059b7263d2bb58f066eb25753)
You can change the language here: 
1) http://prntscr.com/kiiutk
2) http://prntscr.com/kiiv5r

**Comment by israellevin** [comment]
This seems to work, but the language in the selector doesn't change. So after I select "Russian", the texts change to Russian, but the selection box still says "English".

**Comment by DenisDemyanko** [comment]
Fixed in [b24b659](https://github.com/paket-core/mobile/commit/b24b65954fa30a0ed789c388f103f3b419daf76d)
