### ISSUE TITLE
Prepare for changing endpoint subdomains

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#49]
As we have discussed, we are splitting the servers. Set up four constants for the bridge server, the routing server, the funding server, and the identity server, and use them in all calls. Currently, bridge and routing will be set to api.paket.global, funding will be set to fund.paket.global, and identity will be set to identity.paket.global.

**Comment by DenisDemyanko** [comment]
Prepared in [bfe5b86](https://github.com/paket-core/mobile/commit/bfe5b86ad72a078059b7263d2bb58f066eb25753)
