### ISSUE TITLE
Get the app into Android and Apple stores

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#55]

**Comment by DenisDemyanko** [comment]
@israellevin 
Please provide information:

1) App name
2) Description
3) Keywords

**Comment by israellevin** [comment]
This is what we have now, will probably change a lot :)

1. DeliverIt
2. Send and receive packages on the PAKET blockchain, and become a courier to earn money
3. blockchain, delivery, deliveries, last-mile, tokens, crypto, cryptocurrency, earn tokens, earn crypto, earn cryptocurrency, courier, package, send package, paket, distributed, decentralized

**Comment by DenisDemyanko** [comment]
@israellevin 
I think we need more detailed description.

**Comment by israellevin** [comment]
How many words?

**Comment by DenisDemyanko** [comment]
Is not limited.
Must contain:
Description of the application, detailed characteristics and functionality.

**Comment by israellevin** [comment]
App Description:

Send and receive packages on the PAKET blockchain, or become a courier and earn money.

This mobile application makes full use of L1 of the PAKET protocol, which lets users:
1) Launch packages while promising payment and demanding collateral
2) Courier packages, depositing collateral and earning payment
3) Receive packages on the network

The app also features a fully functional BUL wallet, supporting the generation and registration of accounts and the sending and receiving  of BUL tokens.

Finally, the app interacts with the PAKET funding server, allowing users to generate and fund Stellar accounts and to purchase BUL tokens using other cryptocurrencies.

**Comment by DenisDemyanko** [comment]
@israellevin 
Do we need to change the icon or use the existing one?

**Comment by israellevin** [comment]
Use existing one for now, we will update when we have something better.

**Comment by israellevin** [comment]
https://play.google.com/store/apps/details?id=com.paket.PaketGlobal
