### ISSUE TITLE
Error in displaying unique phone number error

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#67]
On entering a nonunique phone number I see the message:
```
('phone number %s already in use', '+972...')
```

This specific error will probably not be shown again, but please check what went wrong.

**Comment by DenisDemyanko** [comment]
@israellevin 
The issue is not entirely clear. Phone number should be unique. Should the error message be modified? Please give more details as to what should be done here.

**Comment by israellevin** [comment]
@DenisDemyanko , phone number uniqueness is handled on the server side, and there are some changes there, so you are not likely to get that error again. Regardless, there is some problem with the error itself. I actually see the string described above. With the "%s". That can't be right. So please take a look and see what the problem was. Maybe it affects other errors as well. Maybe it was just a typo.

**Comment by DenisDemyanko** [comment]
Added in [beb909d](https://github.com/paket-core/mobile/commit/beb909d2ef7649cc3782af786a266a1515b23690)
