### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#69]
https://github.com/paket-core/mobile/blob/master/change-log.md

**Comment by DenisDemyanko** [comment]
Done.
https://github.com/paket-core/mobile/blob/master/change-log.md

**Comment by israellevin** [comment]
This has to be updated every version/milestone.

**Comment by DenisDemyanko** [comment]
Milestone contains all updates - https://github.com/paket-core/mobile/blob/milestone-1.2.4/change-log.md
i don't merged milestone-1.2.4 in to master.
i will merge later.

**Comment by israellevin** [comment]
Oh, cool. Closing issue.
