### ISSUE TITLE
Change address field to country in registration form

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#75]
In the registration form, we want to stop requiring address, and replace it with a country field. The country should be automatically detected and filled, but it should be possible to change it manually.

If the country chosen is USA, we display an error message: "This application is unavailable in the United States".

**Comment by DenisDemyanko** [comment]
Added in [3da9036](https://github.com/paket-core/mobile/commit/3da9036a0bb80b1a8ff2f9eb50ab6d87ca14cc3d)

**Comment by israellevin** [comment]
This is not exactly what I meant. First of all, I get my country automatically filled in as US. That's wrong. Second, I can fill in a non-existing country and it works fine. That's also wrong. And third, I think it will be more clear if we use a drop-down selection to choose a country (which will help us with non-existing countries too).

**Comment by DenisDemyanko** [comment]
Added in [7f077d7](https://github.com/paket-core/mobile/commit/7f077d7f464c5dfa249da8535321dc5d3db3a432)
