### ISSUE TITLE
Better mnemonic display

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#77]
During registration, when we show the mnemonic, we should show it as a numbered list of words, divided into two columns of six words each. When copying the mnemonic, it will be copied without the line breaks or numbers, of course, but we want to add a small warning next to the copy button: "it is recommended to avoid storing the mnemonic in digital form".

In addition, we want to make the mnemonic words stand out, and not appear as part of the text. Some ideas were to add a box around them, to make them larger, and to use a monospace font. Please consult with Serge.

**Comment by DenisDemyanko** [comment]
Added in [3da9036](https://github.com/paket-core/mobile/commit/3da9036a0bb80b1a8ff2f9eb50ab6d87ca14cc3d)
