### ISSUE TITLE
Remove confirmation dialog on mnemonic phrase

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#78]
Currently, right after showing the mnemonic, there is a dialogue asking the user to confirm he saved it. Since there is text asking the user to save it right before, and a test for the nth word right after, we think this dialogue is unnecessary. Please remove it.

**Comment by DenisDemyanko** [comment]
Added in [3da9036](https://github.com/paket-core/mobile/commit/3da9036a0bb80b1a8ff2f9eb50ab6d87ca14cc3d)
