### ISSUE TITLE
Internal server error when attempting to register a user with non-unique call-sign

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#81]
We need a friendly error message here. In general, let's get some special report every time we show a generic error, so we can replace it with a non-generic error. Maybe use countly for this?

**Comment by DenisDemyanko** [comment]
Added in [a619177](https://github.com/paket-core/mobile/commit/a61917795031da96c2adfbe8b40464d8d1b799cf)

**Comment by DenisDemyanko** [comment]
also all "internal errors" store in "Countly"

**Comment by israellevin** [comment]
Very good.
