### ISSUE TITLE
Show message on empty packages screen

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#82]
When there are no packages on one of the packages lists, we should show some "cute" indication inside the list. Consult with Serge for exact design, but we want something like a sad package-box with the writing "no packages found - send a package now", and a click will take us to launch form.

**Comment by DenisDemyanko** [comment]
Added in [7f077d7](https://github.com/paket-core/mobile/commit/7f077d7f464c5dfa249da8535321dc5d3db3a432)
