### ISSUE TITLE
Fix header colors

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#83]
Currently, some headers have unique colors, while others have a generic color, and one header (profile) has a very strong outstanding color (red). Let's use a unique color for every screen, but keep all the colors close together. You probably should consult with Serge.

**Comment by DenisDemyanko** [comment]
Added in [7f077d7](https://github.com/paket-core/mobile/commit/7f077d7f464c5dfa249da8535321dc5d3db3a432)
