### ISSUE TITLE
Leaner filter widget on available packages screen

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#84]
There is no point in having the word "filter" with that icon and a reset button. A slider with a distance and a writing "maximum distance" is enough.

**Comment by DenisDemyanko** [comment]
Added in [a619177](https://github.com/paket-core/mobile/commit/a61917795031da96c2adfbe8b40464d8d1b799cf)

**Comment by israellevin** [comment]
Just one little fix - when moving the bar the user should instantly see what distance he is choosing. Currently I see a spinner, and only when the spinner stops spinning and I see the results do I also see what distance I selected :man_facepalming:

**Comment by DenisDemyanko** [comment]
Added in [7f077d7](https://github.com/paket-core/mobile/commit/7f077d7f464c5dfa249da8535321dc5d3db3a432)

**Comment by israellevin** [comment]
We are now missing the writing "Maximum distance".

**Comment by DenisDemyanko** [comment]
Added in [beb909d](https://github.com/paket-core/mobile/commit/beb909d2ef7649cc3782af786a266a1515b23690)
