### ISSUE TITLE
Fix progress bar

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#91]
Package cards contain some kind of progress bar, but its behaviour is confusing. The point on the line, which is what one would expect to move, is always at the start of the line, but the beginning of the line becomes thicker and green. This looks a bit like a web video player, where the dot shows where you are in the video and the line shows how much of the video was already buffered. Very confusing.

Please fix it so that the dot itself will move on the line, and the line behind it will be thicker and green.

**Comment by DenisDemyanko** [comment]
Added in [26b3629](https://github.com/paket-core/mobile/commit/26b362944f8e3e28525b5f11cdc5178258716aef)
