### ISSUE TITLE
Running notification behaviour

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#92]
After running the app and exiting it, I have a notification telling me that "PaketGlobal is running". This is confusing, as I would expect that exiting the app will make it stop running...

In addition, when tapping the notification I expect to be taken to the app. Instead, I am taken to the Android setting page for the app.

**Comment by DenisDemyanko** [comment]
@israellevin 
This is standard behavior.
We started the package monitoring services.
This can not be fixed.

**Comment by DenisDemyanko** [comment]
Currently i can change title and description: "PaketGlobal. PaketGlobal is running".

About telegram - yes, telegram using push notifications.

@israellevin 
Please provide new text and description.

**Comment by israellevin** [comment]
"DeliverIt background service is running"

**Comment by israellevin** [comment]
@DenisDemyanko , @yaroslavr-itd , please talk between yourselves and give me an estimate on moving to use push notifications, or any other way that will allow us to get rid of this notification and be more like telegram (so we will have only location service notification, which makes more sense to me).

**Comment by israellevin** [comment]
In case it was not clear: do not do it yet! First give me an estimate so we can decide when and if we want to do this.

**Comment by israellevin** [comment]
@DenisDemyanko , is it possible, instead of having the background service constantly alive, to have it turn on every few minutes, or every hour, or whatever?

**Comment by DenisDemyanko** [comment]
No. The service must be started.
The time of requests is indicated in the service.

**Comment by DenisDemyanko** [comment]
Fixed banner. Added buttons to stop service. 
[beb909d](https://github.com/paket-core/mobile/commit/beb909d2ef7649cc3782af786a266a1515b23690)
