### ISSUE TITLE
Settings file

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#95]
We have some settings that we want to be able to set in debug. The first one I can think of is setting the servers (funding, routing, and bridge). We want these setting to be read from a file, so it will not be available to the user, but we can change it with an editor on the phone itself. This should be pretty simple, right? How long will it take to implement?

**Comment by DenisDemyanko** [comment]
@israellevin 
we need to use online file storage.
I think we can use Google Firebase cloud storage.
when the application starts - we need to download the file and set links to the servers

**Comment by DenisDemyanko** [comment]
Added settings page in [a999bf6 ](https://github.com/paket-core/mobile/commit/a999bf6930b087cf5ac4a1b329838664e87a6c75)
