### ISSUE TITLE
Insufficient funds error should include a button to purchase funds

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#96]
When giving an insufficient funds error, either XLM or BUL, we should have a button for "purchase BUL" or "purchase XLM" accordingly.

**Comment by DenisDemyanko** [comment]
Added in [ea1c906](url
https://github.com/paket-core/mobile/commit/ea1c906c7f2ab27bb1933320f250f539a8db84d1)

**Comment by owlen** [comment]
I don't see a button when launching a package.

**Comment by israellevin** [comment]
@DenisDemyanko , this currently happens only in wallet. Should add to launch form and to accept package by courier form.

**Comment by DenisDemyanko** [comment]
Added in [d0ecae7](https://github.com/paket-core/mobile/commit/d0ecae750aa50020f56df94dae707ac58c1e1c23)
