### ISSUE TITLE
Save draft of forms in case of error

### ISSUE THREAD

**Issue by israellevin** [paket-core/mobile#97]
When we get an error (for example - insufficient funds error on launch form), the entire data entered in the form is lost. Same goes for a crush, or even a deliberate closing of the app. In addition, and for obvious reasons, we will need a "clear form" button.

**Comment by DenisDemyanko** [comment]
When we get an error (for example - insufficient funds error on launch form), the entire data entered in the form is lost

can't reproduce. please see my video.

https://www.dropbox.com/s/cwqwpwdmwjgclpd/2018-10-03%2017.04.31.mp4?dl=0
